version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y apache2 
  pre_build:
    commands:
      - echo Entered the pre_build phase... 
  build:
    commands:
      - echo Entered the build phase.
